# frozen_string_literal: true

source 'https://rubygems.org'

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

gem 'google-cloud-firestore', '2.5.1'
gem "google-protobuf", ">= 3.19.2"
gem 'puma'
gem 'sinatra'
gem 'sinatra-partial'

group :development do
  gem 'rubocop'
end
