steps:
- name: 'alpine'
  args: ['sh', 'ls -l']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag', 'eu.gcr.io/ons-gcr/gcp-projects-dashboard-collector', '.']
images: ['eu.gcr.io/ons-gcr/gcp-projects-dashboard-collector']