apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gcp-dashboard-collector
spec:
  schedule: "0/2 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: dashboard-agent
          containers:
          - name: collector
            image: eu.gcr.io/ons-gcr/gcp-projects-dashboard-collector:latest
            imagePullPolicy: Always
            env:
            - name: FIRESTORE_PROJECT
              value: "census-rh-jt-gke"
            - name: GCP_PROJECTS
              valueFrom:
                configMapKeyRef:
                  name: gcp-projects-dashboard
                  key: gcp-projects
          restartPolicy: Never

